## SETUP file for Travis

dist: bionic

language: node_js
node_js:
 - "node"
 
cache:
  directories:  
    - $HOME/.m2

script:
  - mvn -Dremote.user=$REMOTE_USER -Dremote.password=$REMOTE_PW tomcat7:deploy
