language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_deploy:
  - npm run build
  - tar czvf build.tar.gz -C build .
deploy:
  - provider: pages
    skip_cleanup: true # Don't re-run the tests
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: build
    on:
      tags: true
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "./build.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: surge
    project: ./build/
    skip_cleanup: true

script:
  - npm run build
  - echo 'This line disables tests.'

after_success: - surge --project . 